### ISSUE TITLE
Laravel 5.0

### ISSUE THREAD

**Issue by BrunoQuaresma** [creitive/breadcrumbs#8] opened 2015-01-03 18:37 UTC
Problem 1
   - Installation request for creitive/breadcrumbs dev-master -> satisfiable by creitive/breadcrumbs[dev-master].
   - Conclusion: remove laravel/framework 5.0.x-dev
   - creitive/breadcrumbs dev-master requires illuminate/support 4.x -> satisfiable by illuminate/support[4.0.x-dev, 4.1.x-dev, 4.2.x-dev].
   - don't install illuminate/support 4.0.x-dev|don't install laravel/framework 5.0.x-dev
   - don't install illuminate/support 4.1.x-dev|don't install laravel/framework 5.0.x-dev
   - don't install illuminate/support 4.2.x-dev|don't install laravel/framework 5.0.x-dev
   - Installation request for laravel/framework ~5.0 -> satisfiable by laravel/framework[5.0.x-dev].

**Comment by levacic** [comment] 2015-01-10 14:29
Hi!

Sorry for not replying sooner, holidays and all :)

The problem is due to the dependency  "illuminate/support": "4.x"` - and because Laravel 5 isn't stable yet, I'm not sure whether updating it is the only thing needed to support both 4 and 5, or whether we'll need separate branches for each.

If you know anything more, feel free to tell us, or send a PR - otherwise, we'll wait until L5 is officially released, in order to fix this.

Cheers!

**Comment by sukonovs** [comment] 2015-02-27 18:05
Laravel is officially released. And I see pull request with update to this 5th version. Any chance you may review it? Update would be much appreciated, because I have some projects depended on this component.

**Comment by levacic** [comment] 2015-02-28 13:38
Hey @sukonovs, I've just checked out the PR, and it has some problems, which I'll comment on in the PR itself.

However, I've given this some thought recently, and I'm not really sure at the moment whether it makes sense to have a package for both L4 and L5 at the same time - it seems a bit off to have a package check the framework version within its code, and execute code based on that. Additionally, I've never been completely satisfied that this is a Laravel-specific package, because the core class can certainly be used outside of Laravel (as described in the documentation).

I think a better idea might be to release a standalone breadcrumbs class as version 2.0.0 of this package, and then have separate packages such as `creitive/laravel4-breadcrumbs` and `creitive/laravel5-breadcrumbs` - which would basically be adapters for each of the framework versions. After that, someone using the package without Laravel could simply install `creitive/breadcrumbs` (without the `illuminate/support` cruft), and people using it within Laravel would install the appropriate "adapter" package instead.

What do you think about that approach?

I'll have to do some research on this though, because it might involve some potentially "dangerous" stuff, like changing this repository's URL, and I'm not sure if Packagist deals with that correctly.

**Comment by sukonovs** [comment] 2015-02-28 15:45
I think spliting packages for each version makes sense. Many popular package devlopers are making new repos for l5.

**Comment by levacic** [comment] 2015-03-07 18:56
@sukonovs Hi, sorry for the wait! We've released the [new package](https://github.com/creitive/laravel5-breadcrumbs) that targets Laravel 5. The update process would be to remove the old package before installing the new one, ie.

```sh
composer remove creitive/breadcrumbs
composer require creitive/laravel5-breadcrumbs
```

Let me know if this works correctly for you.

I'll close this issue, as this package is now officially non-Laravel dependent, so if you have any problems with the Laravel 5 package, please open an issue in that repo.

Thanks!

**Closed by levacic** 2015-03-07 18:56 UTC
